/***** Lobxxx Translate Finished ******/
package com.sun.corba.se.PortableActivationIDL;


/**
* com/sun/corba/se/PortableActivationIDL/ServerProxyOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from c:/re/workspace/8-2-build-windows-amd64-cygwin/jdk8u45/3627/corba/src/share/classes/com/sun/corba/se/PortableActivationIDL/activation.idl
* Thursday, April 30, 2015 12:42:08 PM PDT
*/


/** Server callback interface, passed to Activator in registerServer method.
/* <p>
    */
public interface ServerProxyOperations 
{

  /** Shutdown this server.  Returns after orb.shutdown() completes.
  /* <p>
	*/
  void shutdown ();

  /** Install the server.  Returns after the install hook completes
	* execution in the server.
	* <p>
	*  执行在服务器。
	* 
	*/
  void install ();

  /** Uninstall the server.  Returns after the uninstall hook
	* completes execution.
	* <p>
	*  完成执行。
	*/
  void uninstall ();
} // interface ServerProxyOperations
