/***** Lobxxx Translate Finished ******/
/*
 * Copyright (c) 1999, 2013, Oracle and/or its affiliates. All rights reserved.
 * ORACLE PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 */

package java.lang.reflect;

import java.lang.ref.WeakReference;
import java.security.AccessController;
import java.security.PrivilegedAction;
import java.util.Arrays;
import java.util.IdentityHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.concurrent.atomic.AtomicLong;
import java.util.function.BiFunction;
import sun.misc.ProxyGenerator;
import sun.misc.VM;
import sun.reflect.CallerSensitive;
import sun.reflect.Reflection;
import sun.reflect.misc.ReflectUtil;
import sun.security.util.SecurityConstants;

/**
 * {@code Proxy} provides static methods for creating dynamic proxy
 * classes and instances, and it is also the superclass of all
 * dynamic proxy classes created by those methods.
 *
 * <p>To create a proxy for some interface {@code Foo}:
 * <pre>
 *     InvocationHandler handler = new MyInvocationHandler(...);
 *     Class&lt;?&gt; proxyClass = Proxy.getProxyClass(Foo.class.getClassLoader(), Foo.class);
 *     Foo f = (Foo) proxyClass.getConstructor(InvocationHandler.class).
 *                     newInstance(handler);
 * </pre>
 * or more simply:
 * <pre>
 *     Foo f = (Foo) Proxy.newProxyInstance(Foo.class.getClassLoader(),
 *                                          new Class&lt;?&gt;[] { Foo.class },
 *                                          handler);
 * </pre>
 *
 * <p>A <i>dynamic proxy class</i> (simply referred to as a <i>proxy
 * class</i> below) is a class that implements a list of interfaces
 * specified at runtime when the class is created, with behavior as
 * described below.
 *
 * A <i>proxy interface</i> is such an interface that is implemented
 * by a proxy class.
 *
 * A <i>proxy instance</i> is an instance of a proxy class.
 *
 * Each proxy instance has an associated <i>invocation handler</i>
 * object, which implements the interface {@link InvocationHandler}.
 * A method invocation on a proxy instance through one of its proxy
 * interfaces will be dispatched to the {@link InvocationHandler#invoke
 * invoke} method of the instance's invocation handler, passing the proxy
 * instance, a {@code java.lang.reflect.Method} object identifying
 * the method that was invoked, and an array of type {@code Object}
 * containing the arguments.  The invocation handler processes the
 * encoded method invocation as appropriate and the result that it
 * returns will be returned as the result of the method invocation on
 * the proxy instance.
 *
 * <p>A proxy class has the following properties:
 *
 * <ul>
 * <li>Proxy classes are <em>public, final, and not abstract</em> if
 * all proxy interfaces are public.</li>
 *
 * <li>Proxy classes are <em>non-public, final, and not abstract</em> if
 * any of the proxy interfaces is non-public.</li>
 *
 * <li>The unqualified name of a proxy class is unspecified.  The space
 * of class names that begin with the string {@code "$Proxy"}
 * should be, however, reserved for proxy classes.
 *
 * <li>A proxy class extends {@code java.lang.reflect.Proxy}.
 *
 * <li>A proxy class implements exactly the interfaces specified at its
 * creation, in the same order.
 *
 * <li>If a proxy class implements a non-public interface, then it will
 * be defined in the same package as that interface.  Otherwise, the
 * package of a proxy class is also unspecified.  Note that package
 * sealing will not prevent a proxy class from being successfully defined
 * in a particular package at runtime, and neither will classes already
 * defined by the same class loader and the same package with particular
 * signers.
 *
 * <li>Since a proxy class implements all of the interfaces specified at
 * its creation, invoking {@code getInterfaces} on its
 * {@code Class} object will return an array containing the same
 * list of interfaces (in the order specified at its creation), invoking
 * {@code getMethods} on its {@code Class} object will return
 * an array of {@code Method} objects that include all of the
 * methods in those interfaces, and invoking {@code getMethod} will
 * find methods in the proxy interfaces as would be expected.
 *
 * <li>The {@link Proxy#isProxyClass Proxy.isProxyClass} method will
 * return true if it is passed a proxy class-- a class returned by
 * {@code Proxy.getProxyClass} or the class of an object returned by
 * {@code Proxy.newProxyInstance}-- and false otherwise.
 *
 * <li>The {@code java.security.ProtectionDomain} of a proxy class
 * is the same as that of system classes loaded by the bootstrap class
 * loader, such as {@code java.lang.Object}, because the code for a
 * proxy class is generated by trusted system code.  This protection
 * domain will typically be granted
 * {@code java.security.AllPermission}.
 *
 * <li>Each proxy class has one public constructor that takes one argument,
 * an implementation of the interface {@link InvocationHandler}, to set
 * the invocation handler for a proxy instance.  Rather than having to use
 * the reflection API to access the public constructor, a proxy instance
 * can be also be created by calling the {@link Proxy#newProxyInstance
 * Proxy.newProxyInstance} method, which combines the actions of calling
 * {@link Proxy#getProxyClass Proxy.getProxyClass} with invoking the
 * constructor with an invocation handler.
 * </ul>
 *
 * <p>A proxy instance has the following properties:
 *
 * <ul>
 * <li>Given a proxy instance {@code proxy} and one of the
 * interfaces implemented by its proxy class {@code Foo}, the
 * following expression will return true:
 * <pre>
 *     {@code proxy instanceof Foo}
 * </pre>
 * and the following cast operation will succeed (rather than throwing
 * a {@code ClassCastException}):
 * <pre>
 *     {@code (Foo) proxy}
 * </pre>
 *
 * <li>Each proxy instance has an associated invocation handler, the one
 * that was passed to its constructor.  The static
 * {@link Proxy#getInvocationHandler Proxy.getInvocationHandler} method
 * will return the invocation handler associated with the proxy instance
 * passed as its argument.
 *
 * <li>An interface method invocation on a proxy instance will be
 * encoded and dispatched to the invocation handler's {@link
 * InvocationHandler#invoke invoke} method as described in the
 * documentation for that method.
 *
 * <li>An invocation of the {@code hashCode},
 * {@code equals}, or {@code toString} methods declared in
 * {@code java.lang.Object} on a proxy instance will be encoded and
 * dispatched to the invocation handler's {@code invoke} method in
 * the same manner as interface method invocations are encoded and
 * dispatched, as described above.  The declaring class of the
 * {@code Method} object passed to {@code invoke} will be
 * {@code java.lang.Object}.  Other public methods of a proxy
 * instance inherited from {@code java.lang.Object} are not
 * overridden by a proxy class, so invocations of those methods behave
 * like they do for instances of {@code java.lang.Object}.
 * </ul>
 *
 * <h3>Methods Duplicated in Multiple Proxy Interfaces</h3>
 *
 * <p>When two or more interfaces of a proxy class contain a method with
 * the same name and parameter signature, the order of the proxy class's
 * interfaces becomes significant.  When such a <i>duplicate method</i>
 * is invoked on a proxy instance, the {@code Method} object passed
 * to the invocation handler will not necessarily be the one whose
 * declaring class is assignable from the reference type of the interface
 * that the proxy's method was invoked through.  This limitation exists
 * because the corresponding method implementation in the generated proxy
 * class cannot determine which interface it was invoked through.
 * Therefore, when a duplicate method is invoked on a proxy instance,
 * the {@code Method} object for the method in the foremost interface
 * that contains the method (either directly or inherited through a
 * superinterface) in the proxy class's list of interfaces is passed to
 * the invocation handler's {@code invoke} method, regardless of the
 * reference type through which the method invocation occurred.
 *
 * <p>If a proxy interface contains a method with the same name and
 * parameter signature as the {@code hashCode}, {@code equals},
 * or {@code toString} methods of {@code java.lang.Object},
 * when such a method is invoked on a proxy instance, the
 * {@code Method} object passed to the invocation handler will have
 * {@code java.lang.Object} as its declaring class.  In other words,
 * the public, non-final methods of {@code java.lang.Object}
 * logically precede all of the proxy interfaces for the determination of
 * which {@code Method} object to pass to the invocation handler.
 *
 * <p>Note also that when a duplicate method is dispatched to an
 * invocation handler, the {@code invoke} method may only throw
 * checked exception types that are assignable to one of the exception
 * types in the {@code throws} clause of the method in <i>all</i> of
 * the proxy interfaces that it can be invoked through.  If the
 * {@code invoke} method throws a checked exception that is not
 * assignable to any of the exception types declared by the method in one
 * of the proxy interfaces that it can be invoked through, then an
 * unchecked {@code UndeclaredThrowableException} will be thrown by
 * the invocation on the proxy instance.  This restriction means that not
 * all of the exception types returned by invoking
 * {@code getExceptionTypes} on the {@code Method} object
 * passed to the {@code invoke} method can necessarily be thrown
 * successfully by the {@code invoke} method.
 *
 * <p>
 *  {@code Proxy}提供了用于创建动态代理类和实例的静态方法,它也是由这些方法创建的所有动态代理类的超类。
 * 
 *  <p>为某个界面创建代理{@code Foo}：
 * <pre>
 *  InvocationHandler handler = new MyInvocationHandler(...);类&lt;?&gt; proxyClass = Proxy.getProxyClass
 * (Foo.class.getClassLoader(),Foo.class); Foo f =(Foo)proxyClass.getConstructor(InvocationHandler.class
 * )。
 *  newInstance(handler);。
 * </pre>
 *  或更简单地：
 * <pre>
 *  Foo f =(Foo)Proxy.newProxyInstance(Foo.class.getClassLoader(),new Class&lt;?&gt; [] {Foo.class},hand
 * ler);。
 * </pre>
 * 
 *  <p>动态代理类</i>(以下简称为<i>代理类</i>)是实现在创建类时在运行时指定的接口列表的类,行为如下所述。
 * 
 *  </i>代理接口是通过代理类实现的接口。
 * 
 *  </i>代理实例</i>是代理类的实例。
 * 
 * 每个代理实例都有一个相关的<i>调用处理程序</i>对象,它实现了接口{@link InvocationHandler}。
 * 通过其代理接口之一在代理实例上的方法调用将被分派到实例的调用处理程序的{@link InvocationHandler#invoke invoke}方法,传递代理实例{@code java.lang.reflect.Method}
 * 对象标识被调用的方法,以及一个包含参数的类型为{@code Object}的数组。
 * 每个代理实例都有一个相关的<i>调用处理程序</i>对象,它实现了接口{@link InvocationHandler}。
 * 调用处理程序适当地处理编码的方法调用,并且返回的结果将作为对代理实例的方法调用的结果而返回。
 * 
 *  <p>代理类具有以下属性：
 * 
 * <ul>
 *  <li>如果所有代理接口都是公共的,代理类是<em> public,final和不抽象</em>。</li>
 * 
 *  <li>如果任何代理接口是非公开的,代理类是非公开的,最终的,而不是抽象的</em>。</li>
 * 
 *  <li>未指定代理类的无限定名称。但是,以字符串{@code"$ Proxy"}开头的类名的空格应该保留给代理类。
 * 
 *  <li>代理类扩展{@code java.lang.reflect.Proxy}。
 * 
 *  <li>代理类在创建时完全按照相同的顺序实现指定的接口。
 * 
 * <li>如果代理类实现了非公共接口,那么它将在与该接口相同的包中定义。否则,代理类的包也是未指定的。
 * 注意,包密封不会阻止在运行时在特定包中成功定义代理类,也不会阻止由同一类装载器定义的类以及具有特定签名者的同一包。
 * 
 *  <li>由于代理类实现了在其创建时指定的所有接口,在其{@code Class}对象上调用{@code getInterfaces}将返回一个包含相同的接口列表的数组(按照创建时指定的顺序) ,在其{@code Class}
 * 对象上调用{@code getMethods}将返回一个包含这些接口中所有方法的{@code Method}对象数组,调用{@code getMethod}会在代理接口中找到方法如预期。
 * 
 *  <li>如果{@link Proxy#isProxyClass Proxy.isProxyClass}方法传递的是代理类(由{@code Proxy.getProxyClass}返回的类或由{@code Proxy)返回的对象的类.newProxyInstance}
 *   - 否则为false。
 * 
 * <li>代理类的{@code java.security.ProtectionDomain}与引导类加载器所加载的系统类相同,例如{@code java.lang.Object},因为代理的代码类由可信
 * 系统代码生成。
 * 此保护域通常将被授予{@code java.security.AllPermission}。
 * 
 *  <li>每个代理类都有一个公共构造函数,它接受一个参数,即{@link InvocationHandler}接口的实现,以设置代理实例的调用处理程序。
 * 而不是必须使用反射API访问公共构造函数,还可以通过调用{@link Proxy#newProxyInstance Proxy.newProxyInstance}方法创建代理实例,该方法将调用{@link Proxy#getProxyClass Proxy .getProxyClass}
 * 使用调用处理程序调用构造函数。
 *  <li>每个代理类都有一个公共构造函数,它接受一个参数,即{@link InvocationHandler}接口的实现,以设置代理实例的调用处理程序。
 * </ul>
 * 
 *  <p>代理实例具有以下属性：
 * 
 * <ul>
 *  <li>假设代理实例{@code proxy}和其代理类{@code Foo}实现的其中一个接口,以下表达式将返回true：
 * <pre>
 *  {@code proxy instanceof Foo}
 * </pre>
 *  并且以下强制转换操作将成功(而不是抛出{@code ClassCastException})：
 * <pre>
 *  {@code(Foo)proxy}
 * </pre>
 * 
 * <li>每个代理实例都有一个关联的调用处理程序,即传递给其构造函数的调用处理程序。
 * 静态{@link Proxy#getInvocationHandler Proxy.getInvocationHandler}方法将返回与作为其参数传递的代理实例相关联的调用处理程序。
 * 
 *  <li>代理实例上的接口方法调用将被编码并调度到调用处理程序的{@link InvocationHandler#invoke invoke}方法,如该方法的文档中所述。
 * 
 *  <li>对代理实例上{@code java.lang.Object}中声明的{@code hashCode},{@code equals}或{@code toString}方法的调用将被编码并分派给调
 * 用处理程序{@code invoke}方法的方式与接口方法调用的编码和调度方式相同,如上所述。
 * 传递给{@code invoke}的{@code Method}对象的声明类将是{@code java.lang.Object}。
 * 从{@code java.lang.Object}继承的代理实例的其他公共方法不会被代理类覆盖,因此调用这些方法的行为就像对{@code java.lang.Object}的实例。
 * </ul>
 * 
 *  <h3>多重代理接口中重复的方法</h3>
 * 
 * <p>当代理类的两个或多个接口包含具有相同名称和参数签名的方法时,代理类接口的顺序变得重要。
 * 当在代理实例上调用这样的<i>重复方法</i>时,传递给调用处理程序的{@code Method}对象不一定是其声明类可从接口的引用类型通过调用代理的方法。
 * 存在此限制,因为生成的代理类中的相应方法实现无法确定通过哪个接口调用它。
 * 因此,当在代理实例上调用重复方法时,在代理类的接口列表中包含方法(直接或通过超级接口继承)的最前面接口中的方法的{@code Method}对象将传递给调用处理程序的{@code invoke}方法,而
 * 不管方法调用发生的引用类型。
 * 存在此限制,因为生成的代理类中的相应方法实现无法确定通过哪个接口调用它。
 * 
 * <p>如果代理接口包含与{@code java.lang.Object}的{@code hashCode},{@code equals}或{@code toString}方法具有相同名称和参数签名的方法
 * ,这样的方法在代理实例上调用,传递给调用处理程序的{@code Method}对象将具有{@code java.lang.Object}作为其声明类。
 * 换句话说,{@code java.lang.Object}的公共非最终方法在所有代理接口之前逻辑地先于确定哪个{@code Method}对象传递给调用处理程序。
 * 
 *  <p>请注意,当重复方法分派到调用处理程序时,{@code invoke}方法只能引用可分配给方法的{@code throws}子句中的某个异常类型的检查异常类型在<i>所有</i>代理接口中,它可以
 * 通过它调用。
 * 如果{@code invoke}方法抛出一个无法分配给该方法在其中一个代理接口中声明的任何异常类型的已检查异常,那么将抛出未经检查的{@code UndeclaredThrowableException}
 * 通过对代理实例的调用。
 * 这种限制意味着,并非所有通过在传递给{@code invoke}方法的{@code Method}对象上调用{@code getExceptionTypes}返回的异常类型都可以被{@code invoke}
 * 方法成功抛出。
 * 
 * 
 * @author      Peter Jones
 * @see         InvocationHandler
 * @since       1.3
 */
public class Proxy implements java.io.Serializable {

    private static final long serialVersionUID = -2222568056686623797L;

    /** parameter types of a proxy class constructor */
    private static final Class<?>[] constructorParams =
        { InvocationHandler.class };

    /**
     * a cache of proxy classes
     * <p>
     *  代理类的缓存
     * 
     */
    private static final WeakCache<ClassLoader, Class<?>[], Class<?>>
        proxyClassCache = new WeakCache<>(new KeyFactory(), new ProxyClassFactory());

    /**
     * the invocation handler for this proxy instance.
     * <p>
     *  此代理实例的调用处理程序。
     * 
     * 
     * @serial
     */
    protected InvocationHandler h;

    /**
     * Prohibits instantiation.
     * <p>
     * 禁止实例化。
     * 
     */
    private Proxy() {
    }

    /**
     * Constructs a new {@code Proxy} instance from a subclass
     * (typically, a dynamic proxy class) with the specified value
     * for its invocation handler.
     *
     * <p>
     *  从子类(通常是动态代理类)构造一个新的{@code Proxy}实例,并为其调用处理程序指定值。
     * 
     * 
     * @param  h the invocation handler for this proxy instance
     *
     * @throws NullPointerException if the given invocation handler, {@code h},
     *         is {@code null}.
     */
    protected Proxy(InvocationHandler h) {
        Objects.requireNonNull(h);
        this.h = h;
    }

    /**
     * Returns the {@code java.lang.Class} object for a proxy class
     * given a class loader and an array of interfaces.  The proxy class
     * will be defined by the specified class loader and will implement
     * all of the supplied interfaces.  If any of the given interfaces
     * is non-public, the proxy class will be non-public. If a proxy class
     * for the same permutation of interfaces has already been defined by the
     * class loader, then the existing proxy class will be returned; otherwise,
     * a proxy class for those interfaces will be generated dynamically
     * and defined by the class loader.
     *
     * <p>There are several restrictions on the parameters that may be
     * passed to {@code Proxy.getProxyClass}:
     *
     * <ul>
     * <li>All of the {@code Class} objects in the
     * {@code interfaces} array must represent interfaces, not
     * classes or primitive types.
     *
     * <li>No two elements in the {@code interfaces} array may
     * refer to identical {@code Class} objects.
     *
     * <li>All of the interface types must be visible by name through the
     * specified class loader.  In other words, for class loader
     * {@code cl} and every interface {@code i}, the following
     * expression must be true:
     * <pre>
     *     Class.forName(i.getName(), false, cl) == i
     * </pre>
     *
     * <li>All non-public interfaces must be in the same package;
     * otherwise, it would not be possible for the proxy class to
     * implement all of the interfaces, regardless of what package it is
     * defined in.
     *
     * <li>For any set of member methods of the specified interfaces
     * that have the same signature:
     * <ul>
     * <li>If the return type of any of the methods is a primitive
     * type or void, then all of the methods must have that same
     * return type.
     * <li>Otherwise, one of the methods must have a return type that
     * is assignable to all of the return types of the rest of the
     * methods.
     * </ul>
     *
     * <li>The resulting proxy class must not exceed any limits imposed
     * on classes by the virtual machine.  For example, the VM may limit
     * the number of interfaces that a class may implement to 65535; in
     * that case, the size of the {@code interfaces} array must not
     * exceed 65535.
     * </ul>
     *
     * <p>If any of these restrictions are violated,
     * {@code Proxy.getProxyClass} will throw an
     * {@code IllegalArgumentException}.  If the {@code interfaces}
     * array argument or any of its elements are {@code null}, a
     * {@code NullPointerException} will be thrown.
     *
     * <p>Note that the order of the specified proxy interfaces is
     * significant: two requests for a proxy class with the same combination
     * of interfaces but in a different order will result in two distinct
     * proxy classes.
     *
     * <p>
     *  返回给定类加载器和接口数组的代理类的{@code java.lang.Class}对象。代理类将由指定的类加载器定义,并将实现所有提供的接口。如果任何给定的接口是非公共的,代理类将是非公共的。
     * 如果接口的相同排列的代理类已经由类加载器定义,则将返回现有的代理类;否则,这些接口的代理类将动态生成并由类加载器定义。
     * 
     *  <p>对可传递到{@code Proxy.getProxyClass}的参数有几个限制：
     * 
     * <ul>
     *  <li> {@code interfaces}数组中的所有{@code Class}对象都必须表示接口,而不是类或原始类型。
     * 
     *  <li> {@code interfaces}数组中没有两个元素可能引用相同的{@code Class}对象。
     * 
     *  <li>所有接口类型必须通过指定的类加载器通过名称可见。换句话说,对于类加载器{@code cl}和每个接口{@code i},以下表达式必须为真：
     * <pre>
     *  Class.forName(i.getName(),false,cl)== i
     * </pre>
     * 
     * <li>所有非公共接口必须在同一个包中;否则,代理类不可能实现所有的接口,而不管它定义在什么包中。
     * 
     *  <li>对于具有相同签名的指定接口的任何一组成员方法：
     * <ul>
     *  <li>如果任何方法的返回类型是基本类型或void,那么所有方法必须具有相同的返回类型。 <li>否则,其中一个方法必须具有可分配给其余方法的所有返回类型的返回类型。
     * </ul>
     * 
     *  <li>生成的代理类不得超过虚拟机对类强加的任何限制。例如,VM可以将类可以实现的接口的数量限制为65535;在这种情况下,{@code interfaces}数组的大小不能超过65535。
     * </ul>
     * 
     *  <p>如果违反任何这些限制,{@code Proxy.getProxyClass}会抛出{@code IllegalArgumentException}。
     * 如果{@code interfaces}数组参数或其任何元素是{@code null},将抛出{@code NullPointerException}。
     * 
     *  <p>请注意,指定的代理接口的顺序很重要：对于具有相同接口组合但是顺序不同的代理类的两个请求将导致两个不同的代理类。
     * 
     * 
     * @param   loader the class loader to define the proxy class
     * @param   interfaces the list of interfaces for the proxy class
     *          to implement
     * @return  a proxy class that is defined in the specified class loader
     *          and that implements the specified interfaces
     * @throws  IllegalArgumentException if any of the restrictions on the
     *          parameters that may be passed to {@code getProxyClass}
     *          are violated
     * @throws  SecurityException if a security manager, <em>s</em>, is present
     *          and any of the following conditions is met:
     *          <ul>
     *             <li> the given {@code loader} is {@code null} and
     *             the caller's class loader is not {@code null} and the
     *             invocation of {@link SecurityManager#checkPermission
     *             s.checkPermission} with
     *             {@code RuntimePermission("getClassLoader")} permission
     *             denies access.</li>
     *             <li> for each proxy interface, {@code intf},
     *             the caller's class loader is not the same as or an
     *             ancestor of the class loader for {@code intf} and
     *             invocation of {@link SecurityManager#checkPackageAccess
     *             s.checkPackageAccess()} denies access to {@code intf}.</li>
     *          </ul>

     * @throws  NullPointerException if the {@code interfaces} array
     *          argument or any of its elements are {@code null}
     */
    @CallerSensitive
    public static Class<?> getProxyClass(ClassLoader loader,
                                         Class<?>... interfaces)
        throws IllegalArgumentException
    {
        final Class<?>[] intfs = interfaces.clone();
        final SecurityManager sm = System.getSecurityManager();
        if (sm != null) {
            checkProxyAccess(Reflection.getCallerClass(), loader, intfs);
        }

        return getProxyClass0(loader, intfs);
    }

    /*
     * Check permissions required to create a Proxy class.
     *
     * To define a proxy class, it performs the access checks as in
     * Class.forName (VM will invoke ClassLoader.checkPackageAccess):
     * 1. "getClassLoader" permission check if loader == null
     * 2. checkPackageAccess on the interfaces it implements
     *
     * To get a constructor and new instance of a proxy class, it performs
     * the package access check on the interfaces it implements
     * as in Class.getConstructor.
     *
     * If an interface is non-public, the proxy class must be defined by
     * the defining loader of the interface.  If the caller's class loader
     * is not the same as the defining loader of the interface, the VM
     * will throw IllegalAccessError when the generated proxy class is
     * being defined via the defineClass0 method.
     * <p>
     *  检查创建Proxy类所需的权限。
     * 
     * 要定义一个代理类,它执行访问检查,如Class.forName(VM将调用ClassLoader.checkPackageAccess)：1."getClassLoader"权限检查loader == 
     * null 2. checkPackageAccess在其实现的接口。
     * 
     *  为了获得一个代理类的构造函数和新实例,它在它实现的接口上对Class.getConstructor执行包访问检查。
     * 
     *  如果接口是非公共的,代理类必须由接口的定义加载器定义。
     * 如果调用者的类加载器与接口的定义加载器不同,当通过defineClass0方法定义生成的代理类时,VM将抛出IllegalAccessError。
     * 
     */
    private static void checkProxyAccess(Class<?> caller,
                                         ClassLoader loader,
                                         Class<?>... interfaces)
    {
        SecurityManager sm = System.getSecurityManager();
        if (sm != null) {
            ClassLoader ccl = caller.getClassLoader();
            if (VM.isSystemDomainLoader(loader) && !VM.isSystemDomainLoader(ccl)) {
                sm.checkPermission(SecurityConstants.GET_CLASSLOADER_PERMISSION);
            }
            ReflectUtil.checkProxyPackageAccess(ccl, interfaces);
        }
    }

    /**
     * Generate a proxy class.  Must call the checkProxyAccess method
     * to perform permission checks before calling this.
     * <p>
     *  生成代理类。在调用此方法之前,必须调用checkProxyAccess方法执行权限检查。
     * 
     */
    private static Class<?> getProxyClass0(ClassLoader loader,
                                           Class<?>... interfaces) {
        if (interfaces.length > 65535) {
            throw new IllegalArgumentException("interface limit exceeded");
        }

        // If the proxy class defined by the given loader implementing
        // the given interfaces exists, this will simply return the cached copy;
        // otherwise, it will create the proxy class via the ProxyClassFactory
        return proxyClassCache.get(loader, interfaces);
    }

    /*
     * a key used for proxy class with 0 implemented interfaces
     * <p>
     *  用于具有0个实现的接口的代理类的密钥
     * 
     */
    private static final Object key0 = new Object();

    /*
     * Key1 and Key2 are optimized for the common use of dynamic proxies
     * that implement 1 or 2 interfaces.
     * <p>
     *  Key1和Key2针对实现1或2个接口的动态代理的共同使用进行了优化。
     * 
     */

    /*
     * a key used for proxy class with 1 implemented interface
     * <p>
     *  用于具有1个实现的接口的代理类的密钥
     * 
     */
    private static final class Key1 extends WeakReference<Class<?>> {
        private final int hash;

        Key1(Class<?> intf) {
            super(intf);
            this.hash = intf.hashCode();
        }

        @Override
        public int hashCode() {
            return hash;
        }

        @Override
        public boolean equals(Object obj) {
            Class<?> intf;
            return this == obj ||
                   obj != null &&
                   obj.getClass() == Key1.class &&
                   (intf = get()) != null &&
                   intf == ((Key1) obj).get();
        }
    }

    /*
     * a key used for proxy class with 2 implemented interfaces
     * <p>
     *  用于具有2个实现的接口的代理类的密钥
     * 
     */
    private static final class Key2 extends WeakReference<Class<?>> {
        private final int hash;
        private final WeakReference<Class<?>> ref2;

        Key2(Class<?> intf1, Class<?> intf2) {
            super(intf1);
            hash = 31 * intf1.hashCode() + intf2.hashCode();
            ref2 = new WeakReference<Class<?>>(intf2);
        }

        @Override
        public int hashCode() {
            return hash;
        }

        @Override
        public boolean equals(Object obj) {
            Class<?> intf1, intf2;
            return this == obj ||
                   obj != null &&
                   obj.getClass() == Key2.class &&
                   (intf1 = get()) != null &&
                   intf1 == ((Key2) obj).get() &&
                   (intf2 = ref2.get()) != null &&
                   intf2 == ((Key2) obj).ref2.get();
        }
    }

    /*
     * a key used for proxy class with any number of implemented interfaces
     * (used here for 3 or more only)
     * <p>
     *  用于具有任何数量的实现的接口的代理类的密钥(这里仅用于3个或更多)
     * 
     */
    private static final class KeyX {
        private final int hash;
        private final WeakReference<Class<?>>[] refs;

        @SuppressWarnings("unchecked")
        KeyX(Class<?>[] interfaces) {
            hash = Arrays.hashCode(interfaces);
            refs = (WeakReference<Class<?>>[])new WeakReference<?>[interfaces.length];
            for (int i = 0; i < interfaces.length; i++) {
                refs[i] = new WeakReference<>(interfaces[i]);
            }
        }

        @Override
        public int hashCode() {
            return hash;
        }

        @Override
        public boolean equals(Object obj) {
            return this == obj ||
                   obj != null &&
                   obj.getClass() == KeyX.class &&
                   equals(refs, ((KeyX) obj).refs);
        }

        private static boolean equals(WeakReference<Class<?>>[] refs1,
                                      WeakReference<Class<?>>[] refs2) {
            if (refs1.length != refs2.length) {
                return false;
            }
            for (int i = 0; i < refs1.length; i++) {
                Class<?> intf = refs1[i].get();
                if (intf == null || intf != refs2[i].get()) {
                    return false;
                }
            }
            return true;
        }
    }

    /**
     * A function that maps an array of interfaces to an optimal key where
     * Class objects representing interfaces are weakly referenced.
     * <p>
     *  将接口数组映射到最佳键的函数,其中表示接口的类对象被弱引用。
     * 
     */
    private static final class KeyFactory
        implements BiFunction<ClassLoader, Class<?>[], Object>
    {
        @Override
        public Object apply(ClassLoader classLoader, Class<?>[] interfaces) {
            switch (interfaces.length) {
                case 1: return new Key1(interfaces[0]); // the most frequent
                case 2: return new Key2(interfaces[0], interfaces[1]);
                case 0: return key0;
                default: return new KeyX(interfaces);
            }
        }
    }

    /**
     * A factory function that generates, defines and returns the proxy class given
     * the ClassLoader and array of interfaces.
     * <p>
     *  一个工厂函数,它根据ClassLoader和接口数组生成,定义和返回代理类。
     * 
     */
    private static final class ProxyClassFactory
        implements BiFunction<ClassLoader, Class<?>[], Class<?>>
    {
        // prefix for all proxy class names
        private static final String proxyClassNamePrefix = "$Proxy";

        // next number to use for generation of unique proxy class names
        private static final AtomicLong nextUniqueNumber = new AtomicLong();

        @Override
        public Class<?> apply(ClassLoader loader, Class<?>[] interfaces) {

            Map<Class<?>, Boolean> interfaceSet = new IdentityHashMap<>(interfaces.length);
            for (Class<?> intf : interfaces) {
                /*
                 * Verify that the class loader resolves the name of this
                 * interface to the same Class object.
                 * <p>
                 * 验证类加载器将此接口的名称解析为同一个Class对象。
                 * 
                 */
                Class<?> interfaceClass = null;
                try {
                    interfaceClass = Class.forName(intf.getName(), false, loader);
                } catch (ClassNotFoundException e) {
                }
                if (interfaceClass != intf) {
                    throw new IllegalArgumentException(
                        intf + " is not visible from class loader");
                }
                /*
                 * Verify that the Class object actually represents an
                 * interface.
                 * <p>
                 *  验证Class对象实际上代表一个接口。
                 * 
                 */
                if (!interfaceClass.isInterface()) {
                    throw new IllegalArgumentException(
                        interfaceClass.getName() + " is not an interface");
                }
                /*
                 * Verify that this interface is not a duplicate.
                 * <p>
                 *  验证此接口不是重复的。
                 * 
                 */
                if (interfaceSet.put(interfaceClass, Boolean.TRUE) != null) {
                    throw new IllegalArgumentException(
                        "repeated interface: " + interfaceClass.getName());
                }
            }

            String proxyPkg = null;     // package to define proxy class in
            int accessFlags = Modifier.PUBLIC | Modifier.FINAL;

            /*
             * Record the package of a non-public proxy interface so that the
             * proxy class will be defined in the same package.  Verify that
             * all non-public proxy interfaces are in the same package.
             * <p>
             *  记录非公共代理接口的包,以便代理类将在同一个包中定义。验证所有非公共代理接口是否在同一个包中。
             * 
             */
            for (Class<?> intf : interfaces) {
                int flags = intf.getModifiers();
                if (!Modifier.isPublic(flags)) {
                    accessFlags = Modifier.FINAL;
                    String name = intf.getName();
                    int n = name.lastIndexOf('.');
                    String pkg = ((n == -1) ? "" : name.substring(0, n + 1));
                    if (proxyPkg == null) {
                        proxyPkg = pkg;
                    } else if (!pkg.equals(proxyPkg)) {
                        throw new IllegalArgumentException(
                            "non-public interfaces from different packages");
                    }
                }
            }

            if (proxyPkg == null) {
                // if no non-public proxy interfaces, use com.sun.proxy package
                proxyPkg = ReflectUtil.PROXY_PACKAGE + ".";
            }

            /*
             * Choose a name for the proxy class to generate.
             * <p>
             *  选择要生成的代理类的名称。
             * 
             */
            long num = nextUniqueNumber.getAndIncrement();
            String proxyName = proxyPkg + proxyClassNamePrefix + num;

            /*
             * Generate the specified proxy class.
             * <p>
             *  生成指定的代理类。
             * 
             */
            byte[] proxyClassFile = ProxyGenerator.generateProxyClass(
                proxyName, interfaces, accessFlags);
            try {
                return defineClass0(loader, proxyName,
                                    proxyClassFile, 0, proxyClassFile.length);
            } catch (ClassFormatError e) {
                /*
                 * A ClassFormatError here means that (barring bugs in the
                 * proxy class generation code) there was some other
                 * invalid aspect of the arguments supplied to the proxy
                 * class creation (such as virtual machine limitations
                 * exceeded).
                 * <p>
                 *  ClassFormatError在这里意味着(禁止代理类生成代码中的错误)有一些其他无效的提供给代理类创建的参数的方面(例如超出虚拟机限制)。
                 * 
                 */
                throw new IllegalArgumentException(e.toString());
            }
        }
    }

    /**
     * Returns an instance of a proxy class for the specified interfaces
     * that dispatches method invocations to the specified invocation
     * handler.
     *
     * <p>{@code Proxy.newProxyInstance} throws
     * {@code IllegalArgumentException} for the same reasons that
     * {@code Proxy.getProxyClass} does.
     *
     * <p>
     *  返回向指定的调用处理程序分派方法调用的指定接口的代理类的实例。
     * 
     *  <p> {@ code Proxy.newProxyInstance}因与{@code Proxy.getProxyClass}相同的原因而抛出{@code IllegalArgumentException}
     * 。
     * 
     * 
     * @param   loader the class loader to define the proxy class
     * @param   interfaces the list of interfaces for the proxy class
     *          to implement
     * @param   h the invocation handler to dispatch method invocations to
     * @return  a proxy instance with the specified invocation handler of a
     *          proxy class that is defined by the specified class loader
     *          and that implements the specified interfaces
     * @throws  IllegalArgumentException if any of the restrictions on the
     *          parameters that may be passed to {@code getProxyClass}
     *          are violated
     * @throws  SecurityException if a security manager, <em>s</em>, is present
     *          and any of the following conditions is met:
     *          <ul>
     *          <li> the given {@code loader} is {@code null} and
     *               the caller's class loader is not {@code null} and the
     *               invocation of {@link SecurityManager#checkPermission
     *               s.checkPermission} with
     *               {@code RuntimePermission("getClassLoader")} permission
     *               denies access;</li>
     *          <li> for each proxy interface, {@code intf},
     *               the caller's class loader is not the same as or an
     *               ancestor of the class loader for {@code intf} and
     *               invocation of {@link SecurityManager#checkPackageAccess
     *               s.checkPackageAccess()} denies access to {@code intf};</li>
     *          <li> any of the given proxy interfaces is non-public and the
     *               caller class is not in the same {@linkplain Package runtime package}
     *               as the non-public interface and the invocation of
     *               {@link SecurityManager#checkPermission s.checkPermission} with
     *               {@code ReflectPermission("newProxyInPackage.{package name}")}
     *               permission denies access.</li>
     *          </ul>
     * @throws  NullPointerException if the {@code interfaces} array
     *          argument or any of its elements are {@code null}, or
     *          if the invocation handler, {@code h}, is
     *          {@code null}
     */
    @CallerSensitive
    public static Object newProxyInstance(ClassLoader loader,
                                          Class<?>[] interfaces,
                                          InvocationHandler h)
        throws IllegalArgumentException
    {
        Objects.requireNonNull(h);

        final Class<?>[] intfs = interfaces.clone();
        final SecurityManager sm = System.getSecurityManager();
        if (sm != null) {
            checkProxyAccess(Reflection.getCallerClass(), loader, intfs);
        }

        /*
         * Look up or generate the designated proxy class.
         * <p>
         *  查找或生成指定的代理类。
         * 
         */
        Class<?> cl = getProxyClass0(loader, intfs);

        /*
         * Invoke its constructor with the designated invocation handler.
         * <p>
         *  使用指定的调用处理程序调用其构造函数。
         * 
         */
        try {
            if (sm != null) {
                checkNewProxyPermission(Reflection.getCallerClass(), cl);
            }

            final Constructor<?> cons = cl.getConstructor(constructorParams);
            final InvocationHandler ih = h;
            if (!Modifier.isPublic(cl.getModifiers())) {
                AccessController.doPrivileged(new PrivilegedAction<Void>() {
                    public Void run() {
                        cons.setAccessible(true);
                        return null;
                    }
                });
            }
            return cons.newInstance(new Object[]{h});
        } catch (IllegalAccessException|InstantiationException e) {
            throw new InternalError(e.toString(), e);
        } catch (InvocationTargetException e) {
            Throwable t = e.getCause();
            if (t instanceof RuntimeException) {
                throw (RuntimeException) t;
            } else {
                throw new InternalError(t.toString(), t);
            }
        } catch (NoSuchMethodException e) {
            throw new InternalError(e.toString(), e);
        }
    }

    private static void checkNewProxyPermission(Class<?> caller, Class<?> proxyClass) {
        SecurityManager sm = System.getSecurityManager();
        if (sm != null) {
            if (ReflectUtil.isNonPublicProxyClass(proxyClass)) {
                ClassLoader ccl = caller.getClassLoader();
                ClassLoader pcl = proxyClass.getClassLoader();

                // do permission check if the caller is in a different runtime package
                // of the proxy class
                int n = proxyClass.getName().lastIndexOf('.');
                String pkg = (n == -1) ? "" : proxyClass.getName().substring(0, n);

                n = caller.getName().lastIndexOf('.');
                String callerPkg = (n == -1) ? "" : caller.getName().substring(0, n);

                if (pcl != ccl || !pkg.equals(callerPkg)) {
                    sm.checkPermission(new ReflectPermission("newProxyInPackage." + pkg));
                }
            }
        }
    }

    /**
     * Returns true if and only if the specified class was dynamically
     * generated to be a proxy class using the {@code getProxyClass}
     * method or the {@code newProxyInstance} method.
     *
     * <p>The reliability of this method is important for the ability
     * to use it to make security decisions, so its implementation should
     * not just test if the class in question extends {@code Proxy}.
     *
     * <p>
     *  当且仅当使用{@code getProxyClass}方法或{@code newProxyInstance}方法将指定的类动态生成为代理类时,返回true。
     * 
     *  <p>这种方法的可靠性对于使用它来做出安全决策的能力很重要,所以它的实现不应该仅仅测试所讨论的类是否扩展{@code Proxy}。
     * 
     * 
     * @param   cl the class to test
     * @return  {@code true} if the class is a proxy class and
     *          {@code false} otherwise
     * @throws  NullPointerException if {@code cl} is {@code null}
     */
    public static boolean isProxyClass(Class<?> cl) {
        return Proxy.class.isAssignableFrom(cl) && proxyClassCache.containsValue(cl);
    }

    /**
     * Returns the invocation handler for the specified proxy instance.
     *
     * <p>
     * 返回指定代理实例的调用处理程序。
     * 
     * 
     * @param   proxy the proxy instance to return the invocation handler for
     * @return  the invocation handler for the proxy instance
     * @throws  IllegalArgumentException if the argument is not a
     *          proxy instance
     * @throws  SecurityException if a security manager, <em>s</em>, is present
     *          and the caller's class loader is not the same as or an
     *          ancestor of the class loader for the invocation handler
     *          and invocation of {@link SecurityManager#checkPackageAccess
     *          s.checkPackageAccess()} denies access to the invocation
     *          handler's class.
     */
    @CallerSensitive
    public static InvocationHandler getInvocationHandler(Object proxy)
        throws IllegalArgumentException
    {
        /*
         * Verify that the object is actually a proxy instance.
         * <p>
         *  验证对象实际上是代理实例。
         */
        if (!isProxyClass(proxy.getClass())) {
            throw new IllegalArgumentException("not a proxy instance");
        }

        final Proxy p = (Proxy) proxy;
        final InvocationHandler ih = p.h;
        if (System.getSecurityManager() != null) {
            Class<?> ihClass = ih.getClass();
            Class<?> caller = Reflection.getCallerClass();
            if (ReflectUtil.needsPackageAccessCheck(caller.getClassLoader(),
                                                    ihClass.getClassLoader()))
            {
                ReflectUtil.checkPackageAccess(ihClass);
            }
        }

        return ih;
    }

    private static native Class<?> defineClass0(ClassLoader loader, String name,
                                                byte[] b, int off, int len);
}
