/***** Lobxxx Translate Finished ******/
package org.omg.IOP;


/**
* org/omg/IOP/TAG_ORB_TYPE.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from c:/re/workspace/8-2-build-windows-amd64-cygwin/jdk8u45/3627/corba/src/share/classes/org/omg/PortableInterceptor/IOP.idl
* Thursday, April 30, 2015 12:42:09 PM PDT
*/

public interface TAG_ORB_TYPE
{

  /**
     * It is often useful in the real world to be able to identify the 
     * particular kind of ORB an object reference is coming from, to work 
     * around problems with that particular ORB, or exploit shared 
     * efficiencies. 
     * <p>
     * The <code>TAG_ORB_TYPE</code> component has an associated value of 
     * type unsigned long (Java long), encoded as a CDR encapsulation, 
     * designating an ORB type ID allocated by the OMG for the ORB type of the 
     * originating ORB. Anyone may register any ORB types by submitting 
     * a short (one-paragraph) description of the ORB type to the OMG, 
     * and will receive a new ORB type ID in return. A list of ORB type 
     * descriptions and values will be made available on the OMG web server. 
     * <p>
     * The <code>TAG_ORB_TYPE</code> component can appear at most once in 
     * any IOR profile. For profiles supporting IIOP 1.1 or greater, it 
     * is optionally present.
     * <p>
     *  在现实世界中通常有用的是能够识别对象引用来自的特定类型的ORB,解决该特定ORB的问题,或者利用共享的效率。
     * <p>
     *  <code> TAG_ORB_TYPE </code>组件具有类型为unsigned long(Java long)的关联值,编码为CDR封装,指定由OMG针对始发ORB的ORB类型分配的ORB类型I
     * D。
     */
  public static final int value = (int)(0L);
}
