/***** Lobxxx Translate Finished ******/
package org.omg.IOP;


/**
* org/omg/IOP/TAG_CODE_SETS.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from c:/re/workspace/8-2-build-windows-amd64-cygwin/jdk8u45/3627/corba/src/share/classes/org/omg/PortableInterceptor/IOP.idl
* Thursday, April 30, 2015 12:42:09 PM PDT
*/

public interface TAG_CODE_SETS
{

  /**
     * The code set component of the IOR multi-component profile structure
     * contains:
     * <ul>
     *   <li>server's native char code set and conversion code sets, and</li>
     *   <li>server's native wchar code set and conversion code sets.</li>
     * </ul>
     * Both char and wchar conversion code sets are listed in order of 
     * preference.
     * <p>
     *  IOR多组件轮廓结构的代码集组件包含：
     * <ul>
     *  <li>服务器的本机字符代码集和转换代码集,</li> <li>服务器的本机wchar代码集和转换代码集。</li>
     */
  public static final int value = (int)(1L);
}
