/***** Lobxxx Translate Finished ******/
/*
 * Copyright (c) 1997, 2012, Oracle and/or its affiliates. All rights reserved.
 * ORACLE PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 *
 */


package com.sun.jmx.snmp.agent;



// java imports
//
import java.io.Serializable;
import java.util.Vector;
import java.util.Enumeration;

// jmx imports
//
import com.sun.jmx.snmp.SnmpOid;

/**
 * Represents a SNMP index.
 * An <CODE>SnmpIndex</CODE> is represented as a <CODE>Vector</CODE> of <CODE>SnmpOid</CODE>.
 * <P>
 * This class is used internally and by the classes generated by <CODE>mibgen</CODE>.
 * You should not need to use this class directly.
 *
 * <p><b>This API is a Sun Microsystems internal API  and is subject
 * to change without notice.</b></p>
 * <p>
 *  表示SNMP索引。 <CODE> SnmpIndex </CODE>表示为<CODE>向量</CODE>的<CODE> SnmpOid </CODE>。
 * <P>
 *  此类在内部使用,由<CODE> mibgen </CODE>生成的类使用。你不应该直接使用这个类。
 * 
 *  <p> <b>此API是Sun Microsystems的内部API,如有更改,恕不另行通知。</b> </p>
 * 
 */

public class SnmpIndex implements Serializable {
    private static final long serialVersionUID = 8712159739982192146L;

    /**
     * Initializes an <CODE>SnmpIndex</CODE> using a vector of object identifiers.
     * <P>Following the RFC recommendations, every syntax that is used as a
     * table index should have an object identifier representation. There are
     * some guidelines on how to map the different syntaxes into an object identifier.
     * In the different <CODE>SnmpValue</CODE> classes provided, there is a <CODE>toOid</CODE> method to get
     * the object identifier of the value.
     *
     * <p>
     *  使用对象标识符向量初始化<CODE> SnmpIndex </CODE>。 <P>遵循RFC建议,用作表索引的每个语法都应具有对象标识符表示。有一些关于如何将不同的语法映射到对象标识符的指南。
     * 在提供的不同的<CODE> SnmpValue </CODE>类中,有一个<CODE> toOid </CODE>方法来获取值的对象标识符。
     * 
     * 
     * @param oidList The list of Object Identifiers.
     */
    public SnmpIndex(SnmpOid[] oidList) {
        size= oidList.length;
        for(int i= 0; i <size; i++) {
            // The order is important ...
            //
            oids.addElement(oidList[i]);
        }
    }

    /**
     * Initializes an <CODE>SnmpIndex</CODE> using the specified Object Identifier.
     *
     * <p>
     *  使用指定的对象标识符初始化<CODE> SnmpIndex </CODE>。
     * 
     * 
     * @param oid The Object Identifier.
     */
    public SnmpIndex(SnmpOid oid) {
        oids.addElement(oid);
        size= 1;
    }

    /**
     * Gets the number of Object Identifiers the index is made of.
     *
     * <p>
     *  获取索引所对应的对象标识符的数量。
     * 
     * 
     * @return The number of Object Identifiers.
     */
    public int getNbComponents() {
        return size;
    }

    /**
     * Gets the index as a vector of Object Identifiers.
     *
     * <p>
     *  获取索引作为对象标识符的向量。
     * 
     * 
     * @return The index as a vector.
     */
    public Vector<SnmpOid> getComponents() {
        return oids;
    }

    /**
     * Compares two indexes for equality.
     *
     * <p>
     *  比较两个索引的相等性。
     * 
     * 
     * @param index The index to compare <CODE>this</CODE> with.
     *
     * @return <CODE>true</CODE> if the two indexes are equal, <CODE>false</CODE> otherwise.
     */
    public boolean equals(SnmpIndex index) {

        if (size != index.getNbComponents())
            return false;

        // The two vectors have the same length.
        // Compare each single element ...
        //
        SnmpOid oid1;
        SnmpOid oid2;
        Vector<SnmpOid> components= index.getComponents();
        for(int i=0; i <size; i++) {
            oid1= oids.elementAt(i);
            oid2= components.elementAt(i);
            if (oid1.equals(oid2) == false)
                return false;
        }
        return true;
    }

    /**
     * Compares two indexes.
     *
     * <p>
     *  比较两个索引。
     * 
     * 
     * @param index The index to compare <CODE>this</CODE> with.
     *
     * @return The value 0 if the two OID vectors have the same elements, another value otherwise.
     */
    public int compareTo(SnmpIndex index) {

        int length= index.getNbComponents();
        Vector<SnmpOid> components= index.getComponents();
        SnmpOid oid1;
        SnmpOid oid2;
        int comp;
        for(int i=0; i < size; i++) {
            if ( i > length) {
                // There is no more element in the index
                //
                return 1;
            }
            // Access the element ...
            //
            oid1= oids.elementAt(i);
            oid2= components.elementAt(i);
            comp= oid1.compareTo(oid2);
            if (comp == 0)
                continue;
            return comp;
        }
        return 0;
    }

    /**
     * Returns a <CODE>String</CODE> representation of the index.
     * The different elements are separated by "//".
     *
     * <p>
     *  返回索引的<CODE> String </CODE>表示形式。不同的元素用"//"分隔。
     * 
     * 
     * @return A string representation of the index.
     */
    @Override
    public String toString() {
        final StringBuilder msg= new StringBuilder();
        for(Enumeration<SnmpOid> e= oids.elements(); e.hasMoreElements(); ) {
            SnmpOid val= e.nextElement();
            msg.append("//").append( val.toString());
        }
        return msg.toString();
    }

    // PRIVATE VARIABLES
    //------------------

    /**
     * The list of OIDs.
     * <p>
     *  OID列表。
     * 
     * 
     * @serial
     */
    private Vector<SnmpOid> oids = new Vector<>();

    /**
     * The number of elements in the index.
     * <p>
     *  索引中的元素数。
     * 
     * @serial
     */
    private int size = 0;
}
